/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import ControlPackage.BB;
import ControlPackage.BruteForce;
import ControlPackage.BruteForceMod;
import ControlPackage.Greed;
import ControlPackage.Little;
import ControlPackage.MSTAproximation;
import Data.Graph;
import Tools.OpenFromFile;
import Tools.SaveToFile;
import Tools.Tester;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Włosek
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    Graph g = new Graph();
    private DecimalFormat df = new DecimalFormat("#0.00");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        test = new javax.swing.JButton();
        start = new javax.swing.JLabel();
        interval = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        probe = new javax.swing.JLabel();
        sField = new javax.swing.JTextField();
        iField = new javax.swing.JTextField();
        nField = new javax.swing.JTextField();
        pField = new javax.swing.JTextField();
        brutCHBox = new javax.swing.JCheckBox();
        bbChBox = new javax.swing.JCheckBox();
        greedChBox = new javax.swing.JCheckBox();
        mstChBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        comTestCHBOX = new javax.swing.JCheckBox();
        timeTestCHB = new javax.swing.JCheckBox();
        LittleChBox = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        miastaButt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        daneField = new javax.swing.JTextField();
        liczbaMiastL = new javax.swing.JLabel();
        gLa = new javax.swing.JLabel();
        bbLa = new javax.swing.JLabel();
        mstLa = new javax.swing.JLabel();
        analizujButt = new javax.swing.JButton();
        BBsel = new javax.swing.JCheckBox();
        Greedsel = new javax.swing.JCheckBox();
        MSTse = new javax.swing.JCheckBox();
        LittleSel = new javax.swing.JCheckBox();
        LittleLa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pathBF = new javax.swing.JTextField();
        pathBB = new javax.swing.JTextField();
        pathGreed = new javax.swing.JTextField();
        pathMST = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pathLittle = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(725, 375));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Moduł  doświadczalny"));

        test.setText("Testuj");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });

        start.setText("Start:");

        interval.setText("Skok:");

        number.setText("Ilośc skoków:");

        probe.setText("Ilość próbkowań:");

        brutCHBox.setText("Brut Force");

        bbChBox.setText("BB");

        greedChBox.setText("Greed");

        mstChBox.setText("MST");

        jLabel1.setText("Wybór algorytmu:");

        comTestCHBOX.setText("test dokładności");

        timeTestCHB.setText("test czasowy");

        LittleChBox.setText("Little");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(interval)
                            .addComponent(start))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iField)
                            .addComponent(sField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(probe)
                            .addComponent(number))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nField)
                            .addComponent(pField))))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brutCHBox)
                            .addComponent(bbChBox))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mstChBox)
                            .addComponent(greedChBox)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comTestCHBOX))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(timeTestCHB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(test))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LittleChBox)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start)
                    .addComponent(sField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interval)
                    .addComponent(iField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number)
                    .addComponent(nField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(probe)
                    .addComponent(pField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(comTestCHBOX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeTestCHB)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greedChBox)
                    .addComponent(brutCHBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mstChBox)
                    .addComponent(bbChBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                .addComponent(LittleChBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(test)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Moduł manualny"));
        jPanel2.setPreferredSize(new java.awt.Dimension(220, 345));

        miastaButt.setText("Załaduj plik");
        miastaButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miastaButtActionPerformed(evt);
            }
        });

        jLabel7.setText("Ścieżka do pliku:");

        daneField.setText("D:\\Dane.txt");

        liczbaMiastL.setText("Liczba miast:");

        gLa.setText("Greed:");

        bbLa.setText("BB:");

        mstLa.setText("MST:");

        analizujButt.setText("Analizuj");
        analizujButt.setEnabled(false);
        analizujButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizujButtActionPerformed(evt);
            }
        });

        BBsel.setText("BB");

        Greedsel.setText("Greed");

        MSTse.setText("MST");

        LittleSel.setText("Little");

        LittleLa.setText("Little:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(daneField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bbLa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mstLa)
                                    .addComponent(gLa))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(miastaButt))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(liczbaMiastL))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(analizujButt))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BBsel)
                                    .addComponent(MSTse))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LittleSel)
                                    .addComponent(Greedsel))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LittleLa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(daneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(miastaButt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(liczbaMiastL)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBsel)
                    .addComponent(Greedsel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MSTse)
                    .addComponent(LittleSel))
                .addGap(18, 18, 18)
                .addComponent(gLa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bbLa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mstLa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LittleLa)
                .addGap(22, 22, 22)
                .addComponent(analizujButt)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Zapis wyników"));

        jLabel2.setText("Brute force");

        jLabel3.setText("BB");

        jLabel5.setText("Greed");

        jLabel6.setText("MST");

        pathBF.setText("C:\\KOMB\\bf.txt");

        pathBB.setText("C:\\KOMB\\bb.txt");
        pathBB.setToolTipText("");

        pathGreed.setText("C:\\KOMB\\greed.txt");

        pathMST.setText("C:\\KOMB\\mst.txt");

        jLabel8.setText("Little");

        pathLittle.setText("C:\\KOMB\\little.txt");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(60, 60, 60)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(43, 43, 43)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(52, 52, 52)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(49, 49, 49)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pathMST, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(pathGreed, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(pathBB)
                    .addComponent(pathBF)
                    .addComponent(pathLittle))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pathBF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pathBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pathGreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pathMST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pathLittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
        // TODO add your handling code here:
        int dStart, dInterval, dNumber, dProbe;
        Tester t = new Tester();
        SaveToFile save = new SaveToFile();
        try {

            dStart = Integer.parseInt(sField.getText());
            dInterval = Integer.parseInt(iField.getText());
            dNumber = Integer.parseInt(nField.getText());
            dProbe = Integer.parseInt(pField.getText());
            if (comTestCHBOX.isSelected()) {
                t.runComTest(dStart, dInterval, dNumber, dProbe, brutCHBox.isSelected(), pathBF.getText(), bbChBox.isSelected(), pathBB.getText(), greedChBox.isSelected(), pathGreed.getText(), mstChBox.isSelected(), pathMST.getText(), LittleChBox.isSelected(), pathLittle.getText());

            }

            if (timeTestCHB.isSelected()) {

                if (brutCHBox.isSelected()) {
                    BruteForce brute = new BruteForce();
                    save.stringToFile(pathBF.getText(), "TEST CZASOWY", true, true);
                    t.runTests(brute, pathBF.getText(), dStart, dInterval, dNumber, dProbe);

                }

                if (bbChBox.isSelected()) {
                    BB BFM = new BB();
                    save.stringToFile(pathGreed.getText(), "TEST CZASOWY", true, true);
                    t.runTests(BFM, pathBB.getText(), dStart, dInterval, dNumber, dProbe);
                }

                if (greedChBox.isSelected()) {
                    Greed gread = new Greed();
                    save.stringToFile(pathGreed.getText(), "TEST CZASOWY", true, true);
                    t.runTests(gread, pathGreed.getText(), dStart, dInterval, dNumber, dProbe);

                }

                if (mstChBox.isSelected()) {
                    MSTAproximation mst = new MSTAproximation();
                    save.stringToFile(pathMST.getText(), "TEST CZASOWY", true, true);
                    t.runTests(mst, pathMST.getText(), dStart, dInterval, dNumber, dProbe);

                }
                
                if (LittleChBox.isSelected()) {
                    Little little = new Little();
                    save.stringToFile(pathLittle.getText(), "TEST CZASOWY", true, true);
                    t.runTests(little, pathMST.getText(), dStart, dInterval, dNumber, dProbe);

                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Błędnie wprowadzone dane.\n\nError: " + e);
        }
        JOptionPane.showMessageDialog(null, "Zakończono obliczenia!!!");
    }//GEN-LAST:event_testActionPerformed

    private void miastaButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miastaButtActionPerformed

        OpenFromFile o = new OpenFromFile();
        g.getCities().clear();
        o.openFromFile(daneField.getText(), g);
        g.generateGraph();

        liczbaMiastL.setText("Liczba miast: " + g.getCities().size());
        analizujButt.setEnabled(true);

    }//GEN-LAST:event_miastaButtActionPerformed

    private void analizujButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizujButtActionPerformed

        if (BBsel.isSelected()) {
            BB BFM = new BB();
            gLa.setText("BFM: " + df.format(BFM.startAlgorithm(g.getGraphOfCities()).getLengthOfRoad()));

 
        }

        if (Greedsel.isSelected()) {
            Greed gread = new Greed();
            gLa.setText("Greed: " + df.format(gread.startAlgorithm(g.getGraphOfCities()).getLengthOfRoad()));

        }

        if (MSTse.isSelected()) {
            MSTAproximation mst = new MSTAproximation();
            mstLa.setText("MST: " + df.format(mst.startAlgorithm(g.getGraphOfCities()).getLengthOfRoad()));
        }
        
        if (LittleSel.isSelected()) {
            Little little = new Little();
            LittleLa.setText("LITTLE: " + df.format(little.startAlgorithm(g.getGraphOfCities()).getLengthOfRoad()));
        }

    }//GEN-LAST:event_analizujButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new MainFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BBsel;
    private javax.swing.JCheckBox Greedsel;
    private javax.swing.JCheckBox LittleChBox;
    private javax.swing.JLabel LittleLa;
    private javax.swing.JCheckBox LittleSel;
    private javax.swing.JCheckBox MSTse;
    private javax.swing.JButton analizujButt;
    private javax.swing.JCheckBox bbChBox;
    private javax.swing.JLabel bbLa;
    private javax.swing.JCheckBox brutCHBox;
    private javax.swing.JCheckBox comTestCHBOX;
    private javax.swing.JTextField daneField;
    private javax.swing.JLabel gLa;
    private javax.swing.JCheckBox greedChBox;
    private javax.swing.JTextField iField;
    private javax.swing.JLabel interval;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel liczbaMiastL;
    private javax.swing.JButton miastaButt;
    private javax.swing.JCheckBox mstChBox;
    private javax.swing.JLabel mstLa;
    private javax.swing.JTextField nField;
    private javax.swing.JLabel number;
    private javax.swing.JTextField pField;
    private javax.swing.JTextField pathBB;
    private javax.swing.JTextField pathBF;
    private javax.swing.JTextField pathGreed;
    private javax.swing.JTextField pathLittle;
    private javax.swing.JTextField pathMST;
    private javax.swing.JLabel probe;
    private javax.swing.JTextField sField;
    private javax.swing.JLabel start;
    private javax.swing.JButton test;
    private javax.swing.JCheckBox timeTestCHB;
    // End of variables declaration//GEN-END:variables
}
